
public class InboxSettingsEmailSettings {

	Object inBoxtypeInboxSettingsEmailSettings;
	
	CategoriesInboxEmailSettings CategoriesInboxEmailSettings;
	
	ImportanceMarkerInboxSettingsEmailSettings importanceMarkerInboxSettingsEmailSettings;

	FilteredMailInboxSettingsEmailSettings filteredMailInboxSettingsEmailSettings; 
}
